export const projects = [
  {
    id: 0,
    title: "Matic AI",
    projectStart: "Jan 2025",
    projectEnd: "Ongoing",
    description:
      "Matic AI is an intelligent visual learning platform that transforms educational questions into clear, step-by-step visual answers. It helps users understand complex concepts one step at a time, making learning more intuitive and accessible for all audiences.",
    techStack: [
      "Next.js",
      "TypeScript",
      "AWS Lambda",
      "Node.js",
      "Python",
      "OpenAI",
      "LangChain",
      "TailwindCSS",
      "Vercel",
      "AI/ML",
    ],
    live: "https://matic-rho.vercel.app/",
    github: "https://github.com/imtarunk/main-maticai",
    image: ["/matic-ai-thumbnail.png", "/matic-ai-thumbnail.png"],
  },
  {
    id: 1,
    title: "Clay",
    projectStart: "Apr 2025",
    projectEnd: "Ongoing",
    description:
      "Clay is a decentralized Web3 social media platform built on the Bitcoin Network using Ordinals and BRC-20 protocols. It empowers users to create, share, and monetize content without intermediaries. Focused on privacy, true ownership, and censorship resistance for creators and users.",
    techStack: [
      "Bitcoin",
      "Ordinals",
      "BRC-20",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
    ],
    live: "https://app.clay.codextarun.xyz/", // Replace with your live link
    github: "https://github.com/imtarunk/CLAY", // Replace with your repo
    image: ["/project-1-light.png", "/project-1-dark.png"], // Light/Dark preview images
  },
  {
    id: 2,
    title: "Cryptoview",
    projectStart: "Mar 2025",
    projectEnd: "Ongoing",
    description:
      "Cryptoview is a powerful toolkit built on Solana that simplifies the creation, deployment, and management of SPL tokens using the SPL-Token-2022 standard. Features include token launcher, wallet analysis, airdrop manager, and real-time on-chain insights tailored for developers and projects.",
    techStack: [
      "Solana",
      "Rust",
      "SPL Token 2022",
      "React",
      "TypeScript",
      "Supabase",
      "TailwindCSS",
    ],
    live: "https://crypto-view-five.vercel.app/", // Replace with your live link
    github: "https://github.com/imtarunk/crypto_view", // Replace with your repo
    image: ["/project-2-light.png", "/project-2-dark.png"], // Images
  },
  // {
  //   id: 3,
  //   title: "Rume",
  //   projectStart: "Jan 2025",
  //   projectEnd: "Ongoing",
  //   description:
  //     "Gitbrain is an AI-powered developer assistant that helps with code search, bug fixes, and team collaboration. It integrates vector search, AI chat over repositories, and a collaborative developer workspace.",
  //   techStack: [
  //     "Next.js",
  //     "TypeScript",
  //     "PostgreSQL",
  //     "Prisma",
  //     "Supabase",
  //     "LangChain",
  //     "OpenAI",
  //     "TailwindCSS",
  //   ],
  //   live: "https://gitbrain.dev",
  //   github: "https://github.com/imtarunk/GitBrain-ai",
  //   image: ["/gitbrain-light.png", "/gitbrain-light.png"],
  // },
  {
    id: 4,
    title: "AppX",
    projectStart: "Feb 2025",
    projectEnd: "Ongoing",
    description:
      "AppX is a SaaS builder that allows anyone to create web apps without coding. Features drag-and-drop UI, authentication, database integration, and deployment in one click. Focused on developers, startups, and solopreneurs.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Prisma",
      "AWS",
      "Vercel",
      "TailwindCSS",
    ],
    live: "https://appx.so",
    github: "https://github.com/imtarunk/Appx-ai",
    image: ["/appx-light.png", "/appx-light.png"],
    inactive: true,
  },
  {
    id: 3,
    title: "Rume",
    projectStart: "June 2025",
    projectEnd: "Done",
    description:
      "Resume To Impact. Rume parses your experience using AI to build a world-class portfolio in seconds. Upload your resume (PDF or DOCX) and get a stunning, personalized portfolio site instantly — no manual effort, no friction.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "TailwindCSS",
      "Gemini API",
      "Vercel",
      "Shadcn/UI",
      "AI/ML",
    ],
    live: "https://rume-app-v1.vercel.app/",
    github: "https://github.com/imtarunk/rume-app",
    image: ["/rume-thumbnail.png", "/rume-thumbnail.png"],
  },
  {
    id: 5,
    title: "Spenn",
    projectStart: "Feb 2025",
    projectEnd: "Ongoing",
    description:
      "Track Every Rupee. Just Text the Bot. Send 'food 200' on Telegram — Spenn logs, categorizes, and visualizes your spending in real-time. No apps. No friction. AI-powered expense tracking that lives entirely in your chat.",
    techStack: [
      "Node.js",
      "TypeScript",
      "Telegram Bot API",
      "PostgreSQL",
      "Prisma",
      "Next.js",
      "OpenAI",
      "Vercel",
      "Chart.js",
    ],
    live: "https://spenn.vercel.app/",
    github: "https://github.com/imtarunk/spenn",
    image: ["/spenn-thumbnail.png", "/spenn-thumbnail.png"],
  },
];
