import { ProjectType } from "../types";

export const projects: ProjectType[] = [
  {
    id: 7,
    title: "Kielo",
    projectStart: "Jul 2026",
    projectEnd: "Ongoing",
    description:
      "Decentralized AI inference network — earn from idle GPU/CPU or call 100+ open-source LLMs through one OpenAI-compatible API at a fraction of closed-provider cost.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Node.js",
      "Distributed Systems",
      "LLM Inference",
      "Desktop App",
    ],
    live: "https://kielo.in/",
    github: "https://kielo.in/",
    image: ["/kielo-thumbnail.png", "/kielo-thumbnail.png"],
  },
  {
    id: 6,
    title: "Matic Studio",
    projectStart: "May 2026",
    projectEnd: "Ongoing",
    description:
      "AI-native animation studio that turns briefs, documents, and scripts into production-quality explainers, product demos, and educational video — finished animation, not another timeline.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Python",
      "OpenAI",
      "LangChain",
      "AWS",
    ],
    live: "https://maticstudio.site/",
    github: "https://github.com/imtarunk/matic_v2_marketing",
    image: ["/matic-ai-thumbnail.png", "/matic-ai-thumbnail.png"],
  },
  {
    id: 5,
    title: "Spenn",
    projectStart: "Feb 2025",
    projectEnd: "Ongoing",
    description:
      "AI expense tracking that lives in Telegram. Text 'food 200' — Spenn logs, categorizes, and visualizes spending in real time. No apps, no friction.",
    techStack: [
      "Node.js",
      "TypeScript",
      "Telegram Bot API",
      "PostgreSQL",
      "OpenAI",
      "Next.js",
    ],
    live: "https://spenn.vercel.app/",
    github: "https://github.com/imtarunk/spenn",
    image: ["/spenn-thumbnail.png", "/spenn-thumbnail.png"],
  },
  {
    id: 3,
    title: "Rume",
    projectStart: "June 2025",
    projectEnd: "Done",
    description:
      "AI resume-to-portfolio pipeline. Upload a PDF or DOCX and get a polished, personalized portfolio site in seconds — parsing, layout, and copy handled end-to-end.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "Gemini API",
      "TailwindCSS",
      "Vercel",
    ],
    live: "https://rume-app-v1.vercel.app/",
    github: "https://github.com/imtarunk/rume-app",
    image: ["/rume-thumbnail.png", "/rume-thumbnail.png"],
  },
  {
    id: 1,
    title: "Clay",
    projectStart: "Apr 2025",
    projectEnd: "Ongoing",
    description:
      "Decentralized social platform on Bitcoin Ordinals and BRC-20 — create, share, and monetize content with true ownership and censorship resistance.",
    techStack: [
      "Bitcoin",
      "Ordinals",
      "BRC-20",
      "Next.js",
      "TypeScript",
      "TailwindCSS",
    ],
    live: "https://app.clay.codextarun.xyz/",
    github: "https://github.com/imtarunk/CLAY",
    image: ["/project-1-light.png", "/project-1-dark.png"],
  },
  {
    id: 2,
    title: "Cryptoview",
    projectStart: "Mar 2025",
    projectEnd: "Ongoing",
    description:
      "Solana toolkit for launching and managing SPL Token-2022 assets — token launcher, wallet analysis, airdrops, and live on-chain insights.",
    techStack: [
      "Solana",
      "Rust",
      "SPL Token 2022",
      "React",
      "TypeScript",
      "Supabase",
    ],
    live: "https://crypto-view-five.vercel.app/",
    github: "https://github.com/imtarunk/crypto_view",
    image: ["/project-2-light.png", "/project-2-dark.png"],
  },
  {
    id: 4,
    title: "AppX",
    projectStart: "Feb 2025",
    projectEnd: "Ongoing",
    description:
      "SaaS builder for shipping web apps without code — drag-and-drop UI, auth, database, and one-click deploy for startups and solopreneurs.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Prisma",
      "AWS",
    ],
    live: "https://appx.so",
    github: "https://github.com/imtarunk/Appx-ai",
    image: ["/appx-light.png", "/appx-light.png"],
    inactive: true,
  },
];
