import { IconType } from "react-icons";
import {
  SiNextdotjs,
  SiTypescript,
  SiNodedotjs,
  SiPython,
  SiOpenai,
  SiLangchain,
  SiAmazonwebservices,
  SiReact,
  SiTailwindcss,
  SiPostgresql,
  SiPrisma,
  SiVercel,
  SiSupabase,
  SiBitcoin,
  SiSolana,
  SiRust,
  SiTelegram,
  SiDocker,
  SiGo,
  SiRedis,
} from "react-icons/si";
import { FaServer, FaBrain } from "react-icons/fa";
import { TbApi } from "react-icons/tb";

export const techIcons: Record<string, { icon: IconType; color: string }> = {
  "Next.js": { icon: SiNextdotjs, color: "#FFFFFF" },
  TypeScript: { icon: SiTypescript, color: "#3178C6" },
  "Node.js": { icon: SiNodedotjs, color: "#339933" },
  Python: { icon: SiPython, color: "#3776AB" },
  OpenAI: { icon: SiOpenai, color: "#FFFFFF" },
  LangChain: { icon: SiLangchain, color: "#1C3C3C" },
  AWS: { icon: SiAmazonwebservices, color: "#FF9900" },
  React: { icon: SiReact, color: "#61DAFB" },
  TailwindCSS: { icon: SiTailwindcss, color: "#06B6D4" },
  "Tailwind CSS": { icon: SiTailwindcss, color: "#06B6D4" },
  PostgreSQL: { icon: SiPostgresql, color: "#4169E1" },
  Prisma: { icon: SiPrisma, color: "#FFFFFF" },
  Vercel: { icon: SiVercel, color: "#FFFFFF" },
  Supabase: { icon: SiSupabase, color: "#3FCF8E" },
  Bitcoin: { icon: SiBitcoin, color: "#F7931A" },
  Ordinals: { icon: SiBitcoin, color: "#F7931A" },
  "BRC-20": { icon: SiBitcoin, color: "#F7931A" },
  Solana: { icon: SiSolana, color: "#14F195" },
  Rust: { icon: SiRust, color: "#FFFFFF" },
  "SPL Token 2022": { icon: SiSolana, color: "#9945FF" },
  "Telegram Bot API": { icon: SiTelegram, color: "#26A5E4" },
  "Gemini API": { icon: FaBrain, color: "#8E75B2" },
  Docker: { icon: SiDocker, color: "#2496ED" },
  Go: { icon: SiGo, color: "#00ADD8" },
  Redis: { icon: SiRedis, color: "#DC382D" },
  "Distributed Systems": { icon: FaServer, color: "#60A5FA" },
  "LLM Inference": { icon: FaBrain, color: "#FB7185" },
  "Desktop App": { icon: FaServer, color: "#A3A3A3" },
  "OpenAI SDK": { icon: SiOpenai, color: "#FFFFFF" },
  "AI/ML": { icon: FaBrain, color: "#FB7185" },
  Express: { icon: TbApi, color: "#FFFFFF" },
};
